name: cached_chewie_plus
description: Fork of official chewie [http://github.com/fluttercommunity/chewie] with flutter_cached_video_player_plus.
version: 1.7.4+4
homepage: https://github.com/woodjobber/cached_chewie_plus.git

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  provider: ^6.0.5
#  video_player: ^2.7.0
  flutter_cached_video_player_plus: ^2.1.1+1
#    path: ../../fixLibs/flutter_cached_video_player

  wakelock_plus: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
