name: cached_chewie_plus
description: Fork of official chewie [http://github.com/fluttercommunity/chewie] with flutter_cached_video_player_plus.
version: 1.7.5
homepage: https://github.com/woodjobber/cached_chewie_plus.git

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  provider: ^6.1.2
  # flutter_cached_video_player_plus: ^2.1.3
  flutter_cached_video_player_plus:
    git:
      url: https://github.com/jk-hub/flutter_cached_video_player
      ref: name_space_issue
  wakelock_plus: ^1.2.8    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
